// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!

@file:OptIn(kotlin.wasm.unsafe.UnsafeWasmMemoryApi::class, kotlin.wasm.ExperimentalWasmInterop::class, kotlin.wasm.unsafe.ComponentModelInternalApi::class)
@file:Suppress("REDUNDANT_ELSE_IN_WHEN")

package site.addzero.aio.example.bindings
import site.addzero.aio.example.counter.PluginRootFunctionsExportsImpl

import site.addzero.aio.example.bindings.runtime.*
import kotlin.wasm.unsafe.componentModelRealloc


@kotlin.wasm.WasmImport("aio:plugin/host@2.0.0", "context")
internal external fun __wasm_import_context(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("aio:plugin/host@2.0.0", "now")
internal external fun __wasm_import_now(): kotlin.Long

@kotlin.wasm.WasmImport("aio:plugin/host@2.0.0", "random")
internal external fun __wasm_import_random(p0: kotlin.Int, p1: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("aio:plugin/host@2.0.0", "log")
internal external fun __wasm_import_log(p0: kotlin.Int, p1: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("aio:plugin/host@2.0.0", "authorize")
internal external fun __wasm_import_authorize(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int): kotlin.Unit



@kotlin.wasm.WasmImport("aio:plugin/database@2.0.0", "begin")
internal external fun __wasm_import_begin(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("aio:plugin/database@2.0.0", "query")
internal external fun __wasm_import_query(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("aio:plugin/database@2.0.0", "execute")
internal external fun __wasm_import_execute(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("aio:plugin/database@2.0.0", "finish")
internal external fun __wasm_import_finish(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int): kotlin.Unit



@kotlin.wasm.WasmImport("aio:plugin/storage@2.0.0", "read")
internal external fun __wasm_import_read(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("aio:plugin/storage@2.0.0", "write")
internal external fun __wasm_import_write(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("aio:plugin/storage@2.0.0", "remove")
internal external fun __wasm_import_remove(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int): kotlin.Unit





@kotlin.wasm.WasmImport("aio:plugin/management@2.0.0", "invoke")
internal external fun __wasm_import_invoke(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Int, p7: kotlin.Int, p8: kotlin.Int, p9: kotlin.Int, p10: kotlin.Int, p11: kotlin.Int): kotlin.Unit





@kotlin.wasm.WasmExport("describe")
fun __wasm_export_describe(): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val result: site.addzero.aio.example.bindings.Metadata.Description = PluginRootFunctionsExportsImpl.describe()

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()

  val bytearray = result.label.encodeToByteArray()
  val len = bytearray.size
  val ptr0 = allocator.writeToLinearMemory(bytearray).address.toInt()

  (ptr + 4).ptr.storeInt(len)
  (ptr + 0).ptr.storeInt(ptr0)

  val address26 = allocator.allocate(result.pages.size * (17*4) /*, align_wasm32=4*/).address.toInt()
  for (iter27 in result.pages.withIndex()) {
    val index28 = iter27.index
    val el = iter27.value
    val base = address26 + (index28 * (17*4))

    val bytearray3 = el.id.encodeToByteArray()
    val len2 = bytearray3.size
    val ptr1 = allocator.writeToLinearMemory(bytearray3).address.toInt()

    (base + 4).ptr.storeInt(len2)
    (base + 0).ptr.storeInt(ptr1)

    val bytearray6 = el.label.encodeToByteArray()
    val len5 = bytearray6.size
    val ptr4 = allocator.writeToLinearMemory(bytearray6).address.toInt()

    (base + (3*4)).ptr.storeInt(len5)
    (base + (2*4)).ptr.storeInt(ptr4)

    val bytearray9 = el.entry.encodeToByteArray()
    val len8 = bytearray9.size
    val ptr7 = allocator.writeToLinearMemory(bytearray9).address.toInt()

    (base + (5*4)).ptr.storeInt(len8)
    (base + (4*4)).ptr.storeInt(ptr7)
    val payload10 = el.scene
    if (payload10 != null) {
      (base + (6*4)).ptr.storeByte(1.toByte())

      val bytearray13 = payload10.id.encodeToByteArray()
      val len12 = bytearray13.size
      val ptr11 = allocator.writeToLinearMemory(bytearray13).address.toInt()

      (base + (8*4)).ptr.storeInt(len12)
      (base + (7*4)).ptr.storeInt(ptr11)

      val bytearray16 = payload10.label.encodeToByteArray()
      val len15 = bytearray16.size
      val ptr14 = allocator.writeToLinearMemory(bytearray16).address.toInt()

      (base + (10*4)).ptr.storeInt(len15)
      (base + (9*4)).ptr.storeInt(ptr14)
    } else {
      (base + (6*4)).ptr.storeByte(0.toByte())
    }

    val address = allocator.allocate(el.menuPath.size * (2*4) /*, align_wasm32=4*/).address.toInt()
    for (iter in el.menuPath.withIndex()) {
      val index = iter.index
      val el = iter.value
      val base = address + (index * (2*4))

      val bytearray19 = el.encodeToByteArray()
      val len18 = bytearray19.size
      val ptr17 = allocator.writeToLinearMemory(bytearray19).address.toInt()

      (base + 4).ptr.storeInt(len18)
      (base + 0).ptr.storeInt(ptr17)

    }
    (base + (12*4)).ptr.storeInt(el.menuPath.size)
    (base + (11*4)).ptr.storeInt(address)
    val payload21 = el.permission
    if (payload21 != null) {
      (base + (13*4)).ptr.storeByte(1.toByte())

      val bytearray24 = payload21.encodeToByteArray()
      val len23 = bytearray24.size
      val ptr22 = allocator.writeToLinearMemory(bytearray24).address.toInt()

      (base + (15*4)).ptr.storeInt(len23)
      (base + (14*4)).ptr.storeInt(ptr22)
    } else {
      (base + (13*4)).ptr.storeByte(0.toByte())
    }
    (base + (16*4)).ptr.storeByte(el.surface.ordinal.toByte())

  }
  (ptr + (3*4)).ptr.storeInt(result.pages.size)
  (ptr + (2*4)).ptr.storeInt(address26)
  return ptr
}
}

/* UNUSED
@kotlin.wasm.WasmExport("cabi_post_describe")
fun cabi_post___wasm_export_describe(p0: kotlin.Int) {
  // GuestDeallocateString(len=(p0 + 4).ptr.loadInt(), ptr=(p0 + 0).ptr.loadInt())
  // GuestDeallocateList(len=(p0 + (3*4)).ptr.loadInt(), ptr=(p0 + (2*4)).ptr.loadInt())
  // GuestDeallocateString(len=(base + 4).ptr.loadInt(), ptr=(base + 0).ptr.loadInt())
  // GuestDeallocateString(len=(base + (3*4)).ptr.loadInt(), ptr=(base + (2*4)).ptr.loadInt())
  // GuestDeallocateString(len=(base + (5*4)).ptr.loadInt(), ptr=(base + (4*4)).ptr.loadInt())
  // GuestDeallocateVariant(tag=(base + (6*4)).ptr.loadUByte().toInt())
  // -- GuestDeallocateVariant case: 0
  // -- GuestDeallocateVariant case: 1
  // GuestDeallocateString(len=(base + (8*4)).ptr.loadInt(), ptr=(base + (7*4)).ptr.loadInt())
  // GuestDeallocateString(len=(base + (10*4)).ptr.loadInt(), ptr=(base + (9*4)).ptr.loadInt())
  // GuestDeallocateList(len=(base + (12*4)).ptr.loadInt(), ptr=(base + (11*4)).ptr.loadInt())
  // GuestDeallocateString(len=(base + 4).ptr.loadInt(), ptr=(base + 0).ptr.loadInt())
  // GuestDeallocateVariant(tag=(base + (13*4)).ptr.loadUByte().toInt())
  // -- GuestDeallocateVariant case: 0
  // -- GuestDeallocateVariant case: 1
  // GuestDeallocateString(len=(base + (15*4)).ptr.loadInt(), ptr=(base + (14*4)).ptr.loadInt())

}
*/

@kotlin.wasm.WasmExport("health")
fun __wasm_export_health(): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val result: kotlin.Result<kotlin.Unit> = PluginRootFunctionsExportsImpl.health()

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(3*4), align=4)*/ allocator.allocate((3*4)).address.toInt()
  if (result.isFailure) {
    val payload0 = (result.exceptionOrNull() as site.addzero.aio.example.bindings.runtime.ComponentException).value as kotlin.String
    (ptr + 0).ptr.storeByte(1.toByte())

    val bytearray = payload0.encodeToByteArray()
    val len = bytearray.size
    val ptr1 = allocator.writeToLinearMemory(bytearray).address.toInt()

    (ptr + (2*4)).ptr.storeInt(len)
    (ptr + 4).ptr.storeInt(ptr1)
  } else {
    (ptr + 0).ptr.storeByte(0.toByte())
  }
  return ptr
}
}

/* UNUSED
@kotlin.wasm.WasmExport("cabi_post_health")
fun cabi_post___wasm_export_health(p0: kotlin.Int) {
  // GuestDeallocateVariant(tag=(p0 + 0).ptr.loadUByte().toInt())
  // -- GuestDeallocateVariant case: 0
  // -- GuestDeallocateVariant case: 1
  // GuestDeallocateString(len=(p0 + (2*4)).ptr.loadInt(), ptr=(p0 + 4).ptr.loadInt())

}
*/

@kotlin.wasm.WasmExport("lifecycle")
fun __wasm_export_lifecycle(p0: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val result: kotlin.Result<kotlin.Unit> = PluginRootFunctionsExportsImpl.lifecycle(site.addzero.aio.example.bindings.Transport.Phase.values()[p0])

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(3*4), align=4)*/ allocator.allocate((3*4)).address.toInt()
  if (result.isFailure) {
    val payload0 = (result.exceptionOrNull() as site.addzero.aio.example.bindings.runtime.ComponentException).value as kotlin.String
    (ptr + 0).ptr.storeByte(1.toByte())

    val bytearray = payload0.encodeToByteArray()
    val len = bytearray.size
    val ptr1 = allocator.writeToLinearMemory(bytearray).address.toInt()

    (ptr + (2*4)).ptr.storeInt(len)
    (ptr + 4).ptr.storeInt(ptr1)
  } else {
    (ptr + 0).ptr.storeByte(0.toByte())
  }
  return ptr
}
}

/* UNUSED
@kotlin.wasm.WasmExport("cabi_post_lifecycle")
fun cabi_post___wasm_export_lifecycle(p0: kotlin.Int) {
  // GuestDeallocateVariant(tag=(p0 + 0).ptr.loadUByte().toInt())
  // -- GuestDeallocateVariant case: 0
  // -- GuestDeallocateVariant case: 1
  // GuestDeallocateString(len=(p0 + (2*4)).ptr.loadInt(), ptr=(p0 + 4).ptr.loadInt())

}
*/

@kotlin.wasm.WasmExport("handle")
fun __wasm_export_handle(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Int, p7: kotlin.Int, p8: kotlin.Int, p9: kotlin.Int, p10: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  // OptionLift start
  val option = if (p4== 1) {
    site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM(p5, p6)
  } else {
    null
  }
  // OptionLift end

  val list = kotlin.collections.ArrayList<site.addzero.aio.example.bindings.Transport.Header>(p8)
  for (i in 0 until p8) {
    val base = (p7) + (i * (4*4))

    list.add(site.addzero.aio.example.bindings.Transport.Header(
    site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((base + 0).ptr.loadInt(), (base + 4).ptr.loadInt()),
    site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((base + (2*4)).ptr.loadInt(), (base + (3*4)).ptr.loadInt()),
    ))
  }

  val list0 = kotlin.collections.ArrayList<kotlin.UByte>(p10)
  for (i1 in 0 until p10) {
    val base = (p9) + (i1 * 1)

    list0.add((base + 0).ptr.loadUByte().toInt().toUByte())
  }
  val result: site.addzero.aio.example.bindings.Transport.Response = PluginRootFunctionsExportsImpl.handle(site.addzero.aio.example.bindings.Transport.Request(
  site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM(p0, p1),
  site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM(p2, p3),
  option,
  list,
  list0,
  ))

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(5*4), align=4)*/ allocator.allocate((5*4)).address.toInt()
  (ptr + 0).ptr.storeShort(result.status.toInt().toShort())

  val address = allocator.allocate(result.headers.size * (4*4) /*, align_wasm32=4*/).address.toInt()
  for (iter in result.headers.withIndex()) {
    val index = iter.index
    val el = iter.value
    val base = address + (index * (4*4))

    val bytearray = el.name.encodeToByteArray()
    val len = bytearray.size
    val ptr2 = allocator.writeToLinearMemory(bytearray).address.toInt()

    (base + 4).ptr.storeInt(len)
    (base + 0).ptr.storeInt(ptr2)

    val bytearray5 = el.value.encodeToByteArray()
    val len4 = bytearray5.size
    val ptr3 = allocator.writeToLinearMemory(bytearray5).address.toInt()

    (base + (3*4)).ptr.storeInt(len4)
    (base + (2*4)).ptr.storeInt(ptr3)

  }
  (ptr + (2*4)).ptr.storeInt(result.headers.size)
  (ptr + 4).ptr.storeInt(address)

  val address6 = allocator.allocate(result.body.size * 1 /*, align_wasm32=1*/).address.toInt()
  for (iter7 in result.body.withIndex()) {
    val index8 = iter7.index
    val el = iter7.value
    val base = address6 + (index8 * 1)
    (base + 0).ptr.storeByte(el.toInt().toByte())

  }
  (ptr + (4*4)).ptr.storeInt(result.body.size)
  (ptr + (3*4)).ptr.storeInt(address6)
  return ptr
}
}

/* UNUSED
@kotlin.wasm.WasmExport("cabi_post_handle")
fun cabi_post___wasm_export_handle(p0: kotlin.Int) {
  // GuestDeallocateList(len=(p0 + (2*4)).ptr.loadInt(), ptr=(p0 + 4).ptr.loadInt())
  // GuestDeallocateString(len=(base + 4).ptr.loadInt(), ptr=(base + 0).ptr.loadInt())
  // GuestDeallocateString(len=(base + (3*4)).ptr.loadInt(), ptr=(base + (2*4)).ptr.loadInt())
  // GuestDeallocateList(len=(p0 + (4*4)).ptr.loadInt(), ptr=(p0 + (3*4)).ptr.loadInt())

}
*/
