// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!

@file:OptIn(kotlin.wasm.unsafe.UnsafeWasmMemoryApi::class, kotlin.wasm.ExperimentalWasmInterop::class, kotlin.wasm.unsafe.ComponentModelInternalApi::class)
@file:Suppress("REDUNDANT_ELSE_IN_WHEN")

package site.addzero.aio.example.bindings
import site.addzero.aio.example.counter.PluginRootFunctionsExportsImpl

import site.addzero.aio.example.bindings.runtime.*
import kotlin.wasm.unsafe.componentModelRealloc

@WitInterface("aio:plugin/host@2.0.0")
internal /*external */interface Host {
@WitImport
companion object Import : site.addzero.aio.example.bindings.Host {
  // <editor-fold defaultstate="collapsed" desc="Generated Import Code">
  override fun context(): site.addzero.aio.example.bindings.Host.RequestContext {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
      val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(11*4), align=4)*/ allocator.allocate((11*4)).address.toInt()
      __wasm_import_context(ptr)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      // OptionLift start
      val option = if ((ptr + 0).ptr.loadUByte().toInt()== 1) {
        site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr + 4).ptr.loadInt(), (ptr + (2*4)).ptr.loadInt())
      } else {
        null
      }
      // OptionLift end
      // OptionLift start
      val option0 = if ((ptr + (3*4)).ptr.loadUByte().toInt()== 1) {
        site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr + (4*4)).ptr.loadInt(), (ptr + (5*4)).ptr.loadInt())
      } else {
        null
      }
      // OptionLift end
      // OptionLift start
      val option1 = if ((ptr + (6*4)).ptr.loadUByte().toInt()== 1) {
        site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr + (7*4)).ptr.loadInt(), (ptr + (8*4)).ptr.loadInt())
      } else {
        null
      }
      // OptionLift end
      return site.addzero.aio.example.bindings.Host.RequestContext(
      option,
      option0,
      option1,
      site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr + (9*4)).ptr.loadInt(), (ptr + (10*4)).ptr.loadInt()),
      )
    }
    // </editor-fold>
  }
  override fun now(): kotlin.ULong {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
      val ret: kotlin.Long = __wasm_import_now()
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      return ret.toULong()
    }
    // </editor-fold>
  }
  override fun random(length: kotlin.UInt): kotlin.Result<kotlin.collections.List<kotlin.UByte>> {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
      val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(3*4), align=4)*/ allocator.allocate((3*4)).address.toInt()
      __wasm_import_random(length.toInt(), ptr)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      val result = if ((ptr + 0).ptr.loadUByte().toInt()== 0) {

        val list = kotlin.collections.ArrayList<kotlin.UByte>((ptr + (2*4)).ptr.loadInt())
        for (i in 0 until (ptr + (2*4)).ptr.loadInt()) {
          val base = ((ptr + 4).ptr.loadInt()) + (i * 1)

          list.add((base + 0).ptr.loadUByte().toInt().toUByte())
        }

        kotlin.Result.success<kotlin.collections.List<kotlin.UByte>>(list)
      } else {
        kotlin.Result.failure<kotlin.collections.List<kotlin.UByte>>(site.addzero.aio.example.bindings.runtime.ComponentException(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr + 4).ptr.loadInt(), (ptr + (2*4)).ptr.loadInt())))
      }
      return result
    }
    // </editor-fold>
  }
  override fun log(message: kotlin.String) {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->

      val bytearray = message.encodeToByteArray()
      val len = bytearray.size
      val ptr = allocator.writeToLinearMemory(bytearray).address.toInt()

      __wasm_import_log(ptr, len)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
    }
    // </editor-fold>
  }
  override fun authorize(permission: kotlin.String): kotlin.Result<kotlin.Boolean> {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->

      val bytearray = permission.encodeToByteArray()
      val len = bytearray.size
      val ptr = allocator.writeToLinearMemory(bytearray).address.toInt()

      val ptr0 = /* RETURN_ADDRESS_ALLOC(size_wasm32=(3*4), align=4)*/ allocator.allocate((3*4)).address.toInt()
      __wasm_import_authorize(ptr, len, ptr0)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      val result = if ((ptr0 + 0).ptr.loadUByte().toInt()== 0) {
        kotlin.Result.success<kotlin.Boolean>(((ptr0 + 4).ptr.loadUByte().toInt() != 0))
      } else {
        kotlin.Result.failure<kotlin.Boolean>(site.addzero.aio.example.bindings.runtime.ComponentException(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr0 + 4).ptr.loadInt(), (ptr0 + (2*4)).ptr.loadInt())))
      }
      return result
    }
    // </editor-fold>
  }
  // </editor-fold>
}
  // START OF TYPES


  class RequestContext(
    var tenantId: kotlin.String?,
    var userId: kotlin.String?,
    var sessionId: kotlin.String?,
    var requestId: kotlin.String,
  )

  // END OF TYPES

  fun context(): site.addzero.aio.example.bindings.Host.RequestContext
  fun now(): kotlin.ULong
  fun random(length: kotlin.UInt): kotlin.Result<kotlin.collections.List<kotlin.UByte>>
  fun log(message: kotlin.String)
  fun authorize(permission: kotlin.String): kotlin.Result<kotlin.Boolean>

}

@WitInterface("aio:plugin/database@2.0.0")
internal /*external */interface Database {
@WitImport
companion object Import : site.addzero.aio.example.bindings.Database {
  // <editor-fold defaultstate="collapsed" desc="Generated Import Code">
  override fun begin(): kotlin.Result<kotlin.UInt> {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
      val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(3*4), align=4)*/ allocator.allocate((3*4)).address.toInt()
      __wasm_import_begin(ptr)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      val result = if ((ptr + 0).ptr.loadUByte().toInt()== 0) {
        kotlin.Result.success<kotlin.UInt>((ptr + 4).ptr.loadInt().toUInt())
      } else {
        kotlin.Result.failure<kotlin.UInt>(site.addzero.aio.example.bindings.runtime.ComponentException(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr + 4).ptr.loadInt(), (ptr + (2*4)).ptr.loadInt())))
      }
      return result
    }
    // </editor-fold>
  }
  override fun query(transaction: kotlin.UInt, statement: kotlin.String, parameters: kotlin.collections.List<site.addzero.aio.example.bindings.Database.Value>): kotlin.Result<site.addzero.aio.example.bindings.Database.Rows> {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->

      val bytearray = statement.encodeToByteArray()
      val len = bytearray.size
      val ptr = allocator.writeToLinearMemory(bytearray).address.toInt()


      val address12 = allocator.allocate(parameters.size * (8+2*4) /*, align_wasm32=8*/).address.toInt()
      for (iter13 in parameters.withIndex()) {
        val index14 = iter13.index
        val el = iter13.value
        val base = address12 + (index14 * (8+2*4))
        // VariantLower START
        when (val x = el) {
          is site.addzero.aio.example.bindings.Database.Value.Null -> {
            (base + 0).ptr.storeByte(0.toByte())
          }
          is site.addzero.aio.example.bindings.Database.Value.Boolean -> {
            val payload0 = x.value
            (base + 0).ptr.storeByte(1.toByte())
            (base + 8).ptr.storeByte((if(payload0) 1 else 0).toByte())
          }
          is site.addzero.aio.example.bindings.Database.Value.Integer -> {
            val payload1 = x.value
            (base + 0).ptr.storeByte(2.toByte())
            (base + 8).ptr.storeLong(payload1)
          }
          is site.addzero.aio.example.bindings.Database.Value.Real -> {
            val payload2 = x.value
            (base + 0).ptr.storeByte(3.toByte())
            (base + 8).ptr.storeDouble(payload2)
          }
          is site.addzero.aio.example.bindings.Database.Value.Text -> {
            val payload3 = x.value
            (base + 0).ptr.storeByte(4.toByte())

            val bytearray6 = payload3.encodeToByteArray()
            val len5 = bytearray6.size
            val ptr4 = allocator.writeToLinearMemory(bytearray6).address.toInt()

            (base + (8+1*4)).ptr.storeInt(len5)
            (base + 8).ptr.storeInt(ptr4)
          }
          is site.addzero.aio.example.bindings.Database.Value.Bytes -> {
            val payload7 = x.value
            (base + 0).ptr.storeByte(5.toByte())

            val address = allocator.allocate(payload7.size * 1 /*, align_wasm32=1*/).address.toInt()
            for (iter in payload7.withIndex()) {
              val index = iter.index
              val el = iter.value
              val base = address + (index * 1)
              (base + 0).ptr.storeByte(el.toInt().toByte())

            }
            (base + (8+1*4)).ptr.storeInt(payload7.size)
            (base + 8).ptr.storeInt(address)
          }
          is site.addzero.aio.example.bindings.Database.Value.Json -> {
            val payload8 = x.value
            (base + 0).ptr.storeByte(6.toByte())

            val bytearray11 = payload8.encodeToByteArray()
            val len10 = bytearray11.size
            val ptr9 = allocator.writeToLinearMemory(bytearray11).address.toInt()

            (base + (8+1*4)).ptr.storeInt(len10)
            (base + 8).ptr.storeInt(ptr9)
          }
          else -> error("unreachable")
        }
        // VariantLower END

      }
      val ptr15 = /* RETURN_ADDRESS_ALLOC(size_wasm32=(5*4), align=4)*/ allocator.allocate((5*4)).address.toInt()
      __wasm_import_query(transaction.toInt(), ptr, len, address12, parameters.size, ptr15)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      val result = if ((ptr15 + 0).ptr.loadUByte().toInt()== 0) {

        val list = kotlin.collections.ArrayList<kotlin.String>((ptr15 + (2*4)).ptr.loadInt())
        for (i in 0 until (ptr15 + (2*4)).ptr.loadInt()) {
          val base = ((ptr15 + 4).ptr.loadInt()) + (i * (2*4))

          list.add(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((base + 0).ptr.loadInt(), (base + 4).ptr.loadInt()))
        }

        val list20 = kotlin.collections.ArrayList<kotlin.collections.List<site.addzero.aio.example.bindings.Database.Value>>((ptr15 + (4*4)).ptr.loadInt())
        for (i21 in 0 until (ptr15 + (4*4)).ptr.loadInt()) {
          val base = ((ptr15 + (3*4)).ptr.loadInt()) + (i21 * (2*4))

          val list18 = kotlin.collections.ArrayList<site.addzero.aio.example.bindings.Database.Value>((base + 4).ptr.loadInt())
          for (i19 in 0 until (base + 4).ptr.loadInt()) {
            val base = ((base + 0).ptr.loadInt()) + (i19 * (8+2*4))
            // VariantLift START.
            val variant = when ((base + 0).ptr.loadUByte().toInt()) {
              0 -> {
                site.addzero.aio.example.bindings.Database.Value.Null
              }
              1 -> {
                site.addzero.aio.example.bindings.Database.Value.Boolean(((base + 8).ptr.loadUByte().toInt() != 0))
              }
              2 -> {
                site.addzero.aio.example.bindings.Database.Value.Integer((base + 8).ptr.loadLong())
              }
              3 -> {
                site.addzero.aio.example.bindings.Database.Value.Real((base + 8).ptr.loadDouble())
              }
              4 -> {
                site.addzero.aio.example.bindings.Database.Value.Text(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((base + 8).ptr.loadInt(), (base + (8+1*4)).ptr.loadInt()))
              }
              5 -> {

                val list16 = kotlin.collections.ArrayList<kotlin.UByte>((base + (8+1*4)).ptr.loadInt())
                for (i17 in 0 until (base + (8+1*4)).ptr.loadInt()) {
                  val base = ((base + 8).ptr.loadInt()) + (i17 * 1)

                  list16.add((base + 0).ptr.loadUByte().toInt().toUByte())
                }
                site.addzero.aio.example.bindings.Database.Value.Bytes(list16)
              }
              6 -> {
                site.addzero.aio.example.bindings.Database.Value.Json(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((base + 8).ptr.loadInt(), (base + (8+1*4)).ptr.loadInt()))
              }
              else -> error("unreachable")
            }
            // VariantLift END

            list18.add(variant)
          }

          list20.add(list18)
        }

        kotlin.Result.success<site.addzero.aio.example.bindings.Database.Rows>(site.addzero.aio.example.bindings.Database.Rows(
        list,
        list20,
        ))
      } else {
        kotlin.Result.failure<site.addzero.aio.example.bindings.Database.Rows>(site.addzero.aio.example.bindings.runtime.ComponentException(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr15 + 4).ptr.loadInt(), (ptr15 + (2*4)).ptr.loadInt())))
      }
      return result
    }
    // </editor-fold>
  }
  override fun execute(transaction: kotlin.UInt, statement: kotlin.String, parameters: kotlin.collections.List<site.addzero.aio.example.bindings.Database.Value>): kotlin.Result<kotlin.ULong> {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->

      val bytearray = statement.encodeToByteArray()
      val len = bytearray.size
      val ptr = allocator.writeToLinearMemory(bytearray).address.toInt()


      val address12 = allocator.allocate(parameters.size * (8+2*4) /*, align_wasm32=8*/).address.toInt()
      for (iter13 in parameters.withIndex()) {
        val index14 = iter13.index
        val el = iter13.value
        val base = address12 + (index14 * (8+2*4))
        // VariantLower START
        when (val x = el) {
          is site.addzero.aio.example.bindings.Database.Value.Null -> {
            (base + 0).ptr.storeByte(0.toByte())
          }
          is site.addzero.aio.example.bindings.Database.Value.Boolean -> {
            val payload0 = x.value
            (base + 0).ptr.storeByte(1.toByte())
            (base + 8).ptr.storeByte((if(payload0) 1 else 0).toByte())
          }
          is site.addzero.aio.example.bindings.Database.Value.Integer -> {
            val payload1 = x.value
            (base + 0).ptr.storeByte(2.toByte())
            (base + 8).ptr.storeLong(payload1)
          }
          is site.addzero.aio.example.bindings.Database.Value.Real -> {
            val payload2 = x.value
            (base + 0).ptr.storeByte(3.toByte())
            (base + 8).ptr.storeDouble(payload2)
          }
          is site.addzero.aio.example.bindings.Database.Value.Text -> {
            val payload3 = x.value
            (base + 0).ptr.storeByte(4.toByte())

            val bytearray6 = payload3.encodeToByteArray()
            val len5 = bytearray6.size
            val ptr4 = allocator.writeToLinearMemory(bytearray6).address.toInt()

            (base + (8+1*4)).ptr.storeInt(len5)
            (base + 8).ptr.storeInt(ptr4)
          }
          is site.addzero.aio.example.bindings.Database.Value.Bytes -> {
            val payload7 = x.value
            (base + 0).ptr.storeByte(5.toByte())

            val address = allocator.allocate(payload7.size * 1 /*, align_wasm32=1*/).address.toInt()
            for (iter in payload7.withIndex()) {
              val index = iter.index
              val el = iter.value
              val base = address + (index * 1)
              (base + 0).ptr.storeByte(el.toInt().toByte())

            }
            (base + (8+1*4)).ptr.storeInt(payload7.size)
            (base + 8).ptr.storeInt(address)
          }
          is site.addzero.aio.example.bindings.Database.Value.Json -> {
            val payload8 = x.value
            (base + 0).ptr.storeByte(6.toByte())

            val bytearray11 = payload8.encodeToByteArray()
            val len10 = bytearray11.size
            val ptr9 = allocator.writeToLinearMemory(bytearray11).address.toInt()

            (base + (8+1*4)).ptr.storeInt(len10)
            (base + 8).ptr.storeInt(ptr9)
          }
          else -> error("unreachable")
        }
        // VariantLower END

      }
      val ptr15 = /* RETURN_ADDRESS_ALLOC(size_wasm32=(8+2*4), align=8)*/ allocator.allocate((8+2*4)).address.toInt()
      __wasm_import_execute(transaction.toInt(), ptr, len, address12, parameters.size, ptr15)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      val result = if ((ptr15 + 0).ptr.loadUByte().toInt()== 0) {
        kotlin.Result.success<kotlin.ULong>((ptr15 + 8).ptr.loadLong().toULong())
      } else {
        kotlin.Result.failure<kotlin.ULong>(site.addzero.aio.example.bindings.runtime.ComponentException(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr15 + 8).ptr.loadInt(), (ptr15 + (8+1*4)).ptr.loadInt())))
      }
      return result
    }
    // </editor-fold>
  }
  override fun finish(transaction: kotlin.UInt, commit: kotlin.Boolean): kotlin.Result<kotlin.Unit> {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
      val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(3*4), align=4)*/ allocator.allocate((3*4)).address.toInt()
      __wasm_import_finish(transaction.toInt(), (if(commit) 1 else 0), ptr)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      val result = if ((ptr + 0).ptr.loadUByte().toInt()== 0) {
        kotlin.Result.success<kotlin.Unit>(Unit)
      } else {
        kotlin.Result.failure<kotlin.Unit>(site.addzero.aio.example.bindings.runtime.ComponentException(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr + 4).ptr.loadInt(), (ptr + (2*4)).ptr.loadInt())))
      }
      return result
    }
    // </editor-fold>
  }
  // </editor-fold>
}
  // START OF TYPES


  sealed interface Value{
    object Null : Value
    class Boolean(val value: kotlin.Boolean) : Value
    class Integer(val value: kotlin.Long) : Value
    class Real(val value: kotlin.Double) : Value
    class Text(val value: kotlin.String) : Value
    class Bytes(val value: kotlin.collections.List<kotlin.UByte>) : Value
    class Json(val value: kotlin.String) : Value
  }
  class Rows(
    var columns: kotlin.collections.List<kotlin.String>,
    var values: kotlin.collections.List<kotlin.collections.List<site.addzero.aio.example.bindings.Database.Value>>,
  )

  // END OF TYPES

  fun begin(): kotlin.Result<kotlin.UInt>
  fun query(transaction: kotlin.UInt, statement: kotlin.String, parameters: kotlin.collections.List<site.addzero.aio.example.bindings.Database.Value>): kotlin.Result<site.addzero.aio.example.bindings.Database.Rows>
  fun execute(transaction: kotlin.UInt, statement: kotlin.String, parameters: kotlin.collections.List<site.addzero.aio.example.bindings.Database.Value>): kotlin.Result<kotlin.ULong>
  fun finish(transaction: kotlin.UInt, commit: kotlin.Boolean): kotlin.Result<kotlin.Unit>

}

@WitInterface("aio:plugin/storage@2.0.0")
internal /*external */interface Storage {
@WitImport
companion object Import : site.addzero.aio.example.bindings.Storage {
  // <editor-fold defaultstate="collapsed" desc="Generated Import Code">
  override fun read(path: kotlin.String): kotlin.Result<kotlin.collections.List<kotlin.UByte>> {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->

      val bytearray = path.encodeToByteArray()
      val len = bytearray.size
      val ptr = allocator.writeToLinearMemory(bytearray).address.toInt()

      val ptr0 = /* RETURN_ADDRESS_ALLOC(size_wasm32=(3*4), align=4)*/ allocator.allocate((3*4)).address.toInt()
      __wasm_import_read(ptr, len, ptr0)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      val result = if ((ptr0 + 0).ptr.loadUByte().toInt()== 0) {

        val list = kotlin.collections.ArrayList<kotlin.UByte>((ptr0 + (2*4)).ptr.loadInt())
        for (i in 0 until (ptr0 + (2*4)).ptr.loadInt()) {
          val base = ((ptr0 + 4).ptr.loadInt()) + (i * 1)

          list.add((base + 0).ptr.loadUByte().toInt().toUByte())
        }

        kotlin.Result.success<kotlin.collections.List<kotlin.UByte>>(list)
      } else {
        kotlin.Result.failure<kotlin.collections.List<kotlin.UByte>>(site.addzero.aio.example.bindings.runtime.ComponentException(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr0 + 4).ptr.loadInt(), (ptr0 + (2*4)).ptr.loadInt())))
      }
      return result
    }
    // </editor-fold>
  }
  override fun write(path: kotlin.String, bytes: kotlin.collections.List<kotlin.UByte>): kotlin.Result<kotlin.Unit> {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->

      val bytearray = path.encodeToByteArray()
      val len = bytearray.size
      val ptr = allocator.writeToLinearMemory(bytearray).address.toInt()


      val address = allocator.allocate(bytes.size * 1 /*, align_wasm32=1*/).address.toInt()
      for (iter in bytes.withIndex()) {
        val index = iter.index
        val el = iter.value
        val base = address + (index * 1)
        (base + 0).ptr.storeByte(el.toInt().toByte())

      }
      val ptr0 = /* RETURN_ADDRESS_ALLOC(size_wasm32=(3*4), align=4)*/ allocator.allocate((3*4)).address.toInt()
      __wasm_import_write(ptr, len, address, bytes.size, ptr0)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      val result = if ((ptr0 + 0).ptr.loadUByte().toInt()== 0) {
        kotlin.Result.success<kotlin.Unit>(Unit)
      } else {
        kotlin.Result.failure<kotlin.Unit>(site.addzero.aio.example.bindings.runtime.ComponentException(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr0 + 4).ptr.loadInt(), (ptr0 + (2*4)).ptr.loadInt())))
      }
      return result
    }
    // </editor-fold>
  }
  override fun remove(path: kotlin.String): kotlin.Result<kotlin.Unit> {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->

      val bytearray = path.encodeToByteArray()
      val len = bytearray.size
      val ptr = allocator.writeToLinearMemory(bytearray).address.toInt()

      val ptr0 = /* RETURN_ADDRESS_ALLOC(size_wasm32=(3*4), align=4)*/ allocator.allocate((3*4)).address.toInt()
      __wasm_import_remove(ptr, len, ptr0)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      val result = if ((ptr0 + 0).ptr.loadUByte().toInt()== 0) {
        kotlin.Result.success<kotlin.Unit>(Unit)
      } else {
        kotlin.Result.failure<kotlin.Unit>(site.addzero.aio.example.bindings.runtime.ComponentException(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr0 + 4).ptr.loadInt(), (ptr0 + (2*4)).ptr.loadInt())))
      }
      return result
    }
    // </editor-fold>
  }
  // </editor-fold>
}
  // START OF TYPES


  // END OF TYPES

  fun read(path: kotlin.String): kotlin.Result<kotlin.collections.List<kotlin.UByte>>
  fun write(path: kotlin.String, bytes: kotlin.collections.List<kotlin.UByte>): kotlin.Result<kotlin.Unit>
  fun remove(path: kotlin.String): kotlin.Result<kotlin.Unit>

}

@WitInterface("aio:plugin/transport@2.0.0")
internal /*external */interface Transport {
@WitImport
companion object Import : site.addzero.aio.example.bindings.Transport {
  // <editor-fold defaultstate="collapsed" desc="Generated Import Code">
  // </editor-fold>
}
  // START OF TYPES


  class Header(
    var name: kotlin.String,
    var value: kotlin.String,
  )

  class Request(
    var method: kotlin.String,
    var path: kotlin.String,
    var query: kotlin.String?,
    var headers: kotlin.collections.List<site.addzero.aio.example.bindings.Transport.Header>,
    var body: kotlin.collections.List<kotlin.UByte>,
  )

  class Response(
    var status: kotlin.UShort,
    var headers: kotlin.collections.List<site.addzero.aio.example.bindings.Transport.Header>,
    var body: kotlin.collections.List<kotlin.UByte>,
  )

  enum class Phase {
    PREPARE,
    ACTIVATE,
    DEACTIVATE,
  }

  // END OF TYPES


}

@WitInterface("aio:plugin/management@2.0.0")
internal /*external */interface Management {
@WitImport
companion object Import : site.addzero.aio.example.bindings.Management {
  // <editor-fold defaultstate="collapsed" desc="Generated Import Code">
  override fun invoke(request: site.addzero.aio.example.bindings.Transport.Request): kotlin.Result<site.addzero.aio.example.bindings.Transport.Response> {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->

      val bytearray = request.method.encodeToByteArray()
      val len = bytearray.size
      val ptr = allocator.writeToLinearMemory(bytearray).address.toInt()


      val bytearray2 = request.path.encodeToByteArray()
      val len1 = bytearray2.size
      val ptr0 = allocator.writeToLinearMemory(bytearray2).address.toInt()

      val option: kotlin.Int
      val option7: kotlin.Int
      val option8: kotlin.Int
      val payload3 = request.query
      if (payload3 != null) {

        val bytearray6 = payload3.encodeToByteArray()
        val len5 = bytearray6.size
        val ptr4 = allocator.writeToLinearMemory(bytearray6).address.toInt()

        option = 1
        option7 = ptr4
        option8 = len5
      } else {
        option = 0
        option7 = 0
        option8 = 0
      }

      val address = allocator.allocate(request.headers.size * (4*4) /*, align_wasm32=4*/).address.toInt()
      for (iter in request.headers.withIndex()) {
        val index = iter.index
        val el = iter.value
        val base = address + (index * (4*4))

        val bytearray12 = el.name.encodeToByteArray()
        val len11 = bytearray12.size
        val ptr10 = allocator.writeToLinearMemory(bytearray12).address.toInt()

        (base + 4).ptr.storeInt(len11)
        (base + 0).ptr.storeInt(ptr10)

        val bytearray15 = el.value.encodeToByteArray()
        val len14 = bytearray15.size
        val ptr13 = allocator.writeToLinearMemory(bytearray15).address.toInt()

        (base + (3*4)).ptr.storeInt(len14)
        (base + (2*4)).ptr.storeInt(ptr13)

      }

      val address16 = allocator.allocate(request.body.size * 1 /*, align_wasm32=1*/).address.toInt()
      for (iter17 in request.body.withIndex()) {
        val index18 = iter17.index
        val el = iter17.value
        val base = address16 + (index18 * 1)
        (base + 0).ptr.storeByte(el.toInt().toByte())

      }
      val ptr19 = /* RETURN_ADDRESS_ALLOC(size_wasm32=(6*4), align=4)*/ allocator.allocate((6*4)).address.toInt()
      __wasm_import_invoke(ptr, len, ptr0, len1, option, option7, option8, address, request.headers.size, address16, request.body.size, ptr19)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      val result = if ((ptr19 + 0).ptr.loadUByte().toInt()== 0) {

        val list = kotlin.collections.ArrayList<site.addzero.aio.example.bindings.Transport.Header>((ptr19 + (3*4)).ptr.loadInt())
        for (i in 0 until (ptr19 + (3*4)).ptr.loadInt()) {
          val base = ((ptr19 + (2*4)).ptr.loadInt()) + (i * (4*4))

          list.add(site.addzero.aio.example.bindings.Transport.Header(
          site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((base + 0).ptr.loadInt(), (base + 4).ptr.loadInt()),
          site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((base + (2*4)).ptr.loadInt(), (base + (3*4)).ptr.loadInt()),
          ))
        }

        val list20 = kotlin.collections.ArrayList<kotlin.UByte>((ptr19 + (5*4)).ptr.loadInt())
        for (i21 in 0 until (ptr19 + (5*4)).ptr.loadInt()) {
          val base = ((ptr19 + (4*4)).ptr.loadInt()) + (i21 * 1)

          list20.add((base + 0).ptr.loadUByte().toInt().toUByte())
        }

        kotlin.Result.success<site.addzero.aio.example.bindings.Transport.Response>(site.addzero.aio.example.bindings.Transport.Response(
        (ptr19 + 4).ptr.loadUShort().toInt().toUShort(),
        list,
        list20,
        ))
      } else {
        kotlin.Result.failure<site.addzero.aio.example.bindings.Transport.Response>(site.addzero.aio.example.bindings.runtime.ComponentException(site.addzero.aio.example.bindings.runtime.STRING_FROM_MEM((ptr19 + 4).ptr.loadInt(), (ptr19 + (2*4)).ptr.loadInt())))
      }
      return result
    }
    // </editor-fold>
  }
  // </editor-fold>
}
  // START OF TYPES


  // END OF TYPES

  fun invoke(request: site.addzero.aio.example.bindings.Transport.Request): kotlin.Result<site.addzero.aio.example.bindings.Transport.Response>

}

@WitInterface("aio:plugin/metadata@2.0.0")
internal /*external */interface Metadata {
@WitImport
companion object Import : site.addzero.aio.example.bindings.Metadata {
  // <editor-fold defaultstate="collapsed" desc="Generated Import Code">
  // </editor-fold>
}
  // START OF TYPES


  enum class Surface {
    WORKSPACE,
    FULLSCREEN,
    ACCOUNT_ENTRY,
    ACCOUNT_MENU,
  }

  class Scene(
    var id: kotlin.String,
    var label: kotlin.String,
  )

  class PageDefinition(
    var id: kotlin.String,
    var label: kotlin.String,
    var entry: kotlin.String,
    var scene: site.addzero.aio.example.bindings.Metadata.Scene?,
    var menuPath: kotlin.collections.List<kotlin.String>,
    var permission: kotlin.String?,
    var surface: site.addzero.aio.example.bindings.Metadata.Surface,
  )

  class Description(
    var label: kotlin.String,
    var pages: kotlin.collections.List<site.addzero.aio.example.bindings.Metadata.PageDefinition>,
  )

  // END OF TYPES


}


@WitInterface("\$root")
internal /*external */interface PluginRootFunctions {
  interface Exports{
    fun describe(): site.addzero.aio.example.bindings.Metadata.Description
    fun health(): kotlin.Result<kotlin.Unit>
    fun lifecycle(phase: site.addzero.aio.example.bindings.Transport.Phase): kotlin.Result<kotlin.Unit>
    fun handle(request: site.addzero.aio.example.bindings.Transport.Request): site.addzero.aio.example.bindings.Transport.Response
  }

}
